"""add_website_form_schema_v2

Revision ID: 4873559be294
Revises: 102fb02db316
Create Date: 2026-01-16 17:45:34.587069+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4873559be294'
down_revision: Union[str, Sequence[str], None] = '102fb02db316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tracking_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'domain', name='uq_website_tenant_domain'),
    sa.UniqueConstraint('tracking_id')
    )
    op.create_index(op.f('ix_website_domain'), 'website', ['domain'], unique=False)
    op.create_index(op.f('ix_website_tenant_id'), 'website', ['tenant_id'], unique=False)
    op.create_table('form',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_tenant_id'), 'form', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_form_website_id'), 'form', ['website_id'], unique=False)
    op.add_column('contact', sa.Column('website_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_contact_website_id'), 'contact', ['website_id'], unique=False)
    op.create_unique_constraint('uq_contact_tenant_email', 'contact', ['tenant_id', 'email'])
    op.create_foreign_key(None, 'contact', 'website', ['website_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_constraint('uq_contact_tenant_email', 'contact', type_='unique')
    op.drop_index(op.f('ix_contact_website_id'), table_name='contact')
    op.drop_column('contact', 'website_id')
    op.drop_index(op.f('ix_form_website_id'), table_name='form')
    op.drop_index(op.f('ix_form_tenant_id'), table_name='form')
    op.drop_table('form')
    op.drop_index(op.f('ix_website_tenant_id'), table_name='website')
    op.drop_index(op.f('ix_website_domain'), table_name='website')
    op.drop_table('website')
    # ### end Alembic commands ###
