"""add_is_system_to_website

Revision ID: 9a98c1abd03b
Revises: 4c7770736fb7
Create Date: 2026-01-16 18:41:44.858360+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a98c1abd03b'
down_revision: Union[str, Sequence[str], None] = '4c7770736fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website', sa.Column('is_system', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website', 'is_system')
    # ### end Alembic commands ###
