"""add_form_submission_table

Revision ID: b507cb62116b
Revises: bd9652f24fd1
Create Date: 2026-01-16 17:56:41.514636+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b507cb62116b'
down_revision: Union[str, Sequence[str], None] = 'bd9652f24fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formsubmission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formsubmission_form_id'), 'formsubmission', ['form_id'], unique=False)
    op.create_index(op.f('ix_formsubmission_tenant_id'), 'formsubmission', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_formsubmission_website_id'), 'formsubmission', ['website_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_formsubmission_website_id'), table_name='formsubmission')
    op.drop_index(op.f('ix_formsubmission_tenant_id'), table_name='formsubmission')
    op.drop_index(op.f('ix_formsubmission_form_id'), table_name='formsubmission')
    op.drop_table('formsubmission')
    # ### end Alembic commands ###
